In [1]:
import pandas as pd

In [25]:
import pandas as pd
from glob import glob
import os

# Define the path to the directory containing the JSON files
# Use an absolute or relative path, e.g., 'path/to/json_folder/'
path_to_json_files = '/Users/rowena/Other Projects/external_data_study/Result/cantonfair/' 

# Find all files ending with '.json' in the specified directory
json_files = glob(os.path.join(path_to_json_files, '*.json'))

# Read each file into a DataFrame and concatenate them into a single DataFrame
# The list comprehension efficiently processes all files
df = pd.concat((pd.read_json(f, orient='records', lines=True) for f in json_files), ignore_index=True)

# Display the combined DataFrame
#print(df.head())

In [29]:
df.to_csv(path_to_json_files+'cantonfair.csv',encoding='utf-8-sig',index=False)

In [23]:
pd.concat((pd.read_json(f, orient='records', lines=True) for f in json_files))

,Company_Name,URL,Category,SubCategory
0,"Changchun Walter Storage Equipment Co., Ltd.",https://www.cantonfair.org.cn/en-US/shops/7806...,Hardware & Tools,
1,Hebei Sinostar Trading Co. Ltd,https://www.cantonfair.org.cn/en-US/shops/4516...,Hardware & Tools,
2,"Henansheng YongMo Technology Co., Ltd.",https://www.cantonfair.org.cn/en-US/shops/7805...,Hardware & Tools,
3,"Foshan YouMi Electronic Technology Co., Ltd",https://www.cantonfair.org.cn/en-US/shops/8445...,Hardware & Tools,
4,"GUANGDONG TOPCENT DEVELOPMENT CO.,LTD.",https://www.cantonfair.org.cn/en-US/shops/4516...,Hardware & Tools,
...,...,...,...,...
1995,UNO KUNSHAN INDUSTRIAL INC.,https://www.cantonfair.org.cn/en-US/shops/4516...,Manufacturing,
1996,"QINGYUAN JULI HOISTING MACHINERY CO.,LTD",https://www.cantonfair.org.cn/en-US/shops/4516...,Manufacturing,
1997,"TAIZHOU XUTIAN PACKING MACHINE CO.,LTD",https://www.cantonfair.org.cn/en-US/shops/4516...,Manufacturing,
1998,"CHONGQING LIFAN INDUSTRY(GROUP) IMP.&EXP.CO., LTD",https://www.cantonfair.org.cn/en-US/shops/4516...,Manufacturing,
1999,"CHANGZHOU HUANGHE INTERNATIONAL TRADE CO.,LTD",https://www.cantonfair.org.cn/en-US/shops/4516...,Manufacturing,

In [31]:
chk_df=df.drop_duplicates()

chk_df.to_csv(path_to_json_files+'cantonfair_v1.csv',encoding='utf-8-sig',index=False)

In [136]:
t1=pd.read_json('/Users/rowena/cantonfair_L1.json', orient='records', lines=True)

In [198]:
t2=pd.read_json('/Users/rowena/cantonfair_L1_contact.json', orient='records', lines=True)

In [181]:
pd.isna(t1['company profile'][2708])==False

False

In [193]:
import math

t1['Company Name - Detail']=''
t1['Description']=''
t1['Group Members']=''
t1['Company Type']=''
t1['Registered Capital']=''
t1['Register Date']=''
t1['Enterprise Scale']=''
t1['Trade capacity']=''
t1['Main Products']=''
t1['Company Type']=''
# t1['Country/Region']=''
# t1['Address']=''
# t1['Zip code']=''
# t1['Company website']=''

#"contact information": ["Basic Information", "", "Company Name", "", "Hebei Sinostar Trading Co. Ltd", "", "Country/Region", "", "Hebei,China", "", "Address", "", "No. 39 Xiangyi Road, Xinhua District, Shijiazhuang, Hebei, China", "", "Zip code", "", "050011", "", "Company website", "", "http://www.hbsinostar.com"]

for i in range(len(t1)):
    if type(t1.loc[i,'company profile'])!=float:
        company_profile=t1.loc[i,'company profile']
    #contact_information=t1.loc[i,'contact information']
        t1.loc[i,'Company Name - Detail']=company_profile[company_profile.index("Company Name",3)+2]
        t1.loc[i,'Description']=company_profile[company_profile.index("Enterprise profile",3)+2]
    try:
        t1.loc[i,'Group Members']=company_profile[company_profile.index("GROUP MEMBERS:",3)+2]
    except:
        pass

    try:
        t1.loc[i,'Company Type']=company_profile[company_profile.index("Company type",3)+2]
    except:
        pass
    
    try:
        t1.loc[i,'Registered Capital']=company_profile[company_profile.index("Registered Capital",3)+2]
    except:
        pass
        
    try:
        t1.loc[i,'Register Date']=company_profile[company_profile.index("Register Date",3)+2]
    except:
        pass
    try:
        t1.loc[i,'Enterprise Scale']=company_profile[company_profile.index("Enterprise Scale",3)+2]
    except:
        pass

    try:
        t1.loc[i,'Trade capacity']=company_profile[company_profile.index("Trade capacity",3)+2]

    except:
        pass
    
    try:
        t1.loc[i,'Main Products']=company_profile[company_profile.index("Main Products",3)+2]
    except:
        pass

    #t1.loc[i,'Country/Region']=contact_information[contact_information.index("Country/Region",3)+2]
    #t1.loc[i,'Address']=contact_information[contact_information.index("Address",3)+2]
    #t1.loc[i,'Zip code']=contact_information[contact_information.index("Zip code",3)+2]
    #t1.loc[i,'Company website']=contact_information[contact_information.index("Company website",3)+2]

In [204]:

t2['Country/Region']=''
t2['Address']=''
t2['Zip code']=''
t2['Company website']=''

#"contact information": ["Basic Information", "", "Company Name", "", "Hebei Sinostar Trading Co. Ltd", "", "Country/Region", "", "Hebei,China", "", "Address", "", "No. 39 Xiangyi Road, Xinhua District, Shijiazhuang, Hebei, China", "", "Zip code", "", "050011", "", "Company website", "", "http://www.hbsinostar.com"]

for i in range(len(t2)):
    if type(t2.loc[i,'contact information'])!=float:
        contact_information=t2.loc[i,'contact information']

        t2.loc[i,'Country/Region']=contact_information[contact_information.index("Country/Region",3)+2]
        t2.loc[i,'Address']=contact_information[contact_information.index("Address",3)+2]
        t2.loc[i,'Zip code']=contact_information[contact_information.index("Zip code",3)+2]
        t2.loc[i,'Company website']=contact_information[contact_information.index("Company website",3)+2]

In [195]:
t1.to_csv(path_to_json_files+'cantonfair_v2_co.csv',encoding='utf-8-sig',index=False)

In [206]:
t2.to_csv(path_to_json_files+'cantonfair_v2_contact.csv',encoding='utf-8-sig',index=False)

In [104]:
t1['company profile'][0][t1['company profile'][0].index("Company Name",3)+2]

'GUANG ZHOU AOKING LEATHER CO.,LTD'

In [108]:
df_list=pd.read_csv('/Users/rowena/Other Projects/external_data_study/Result/cantonfair/cantonfair_v1.csv')

In [110]:
df_list

,Company_Name,URL,Category,SubCategory
0,"Changchun Walter Storage Equipment Co., Ltd.",https://www.cantonfair.org.cn/en-US/shops/7806...,Hardware & Tools,NaN
1,Hebei Sinostar Trading Co. Ltd,https://www.cantonfair.org.cn/en-US/shops/4516...,Hardware & Tools,NaN
2,"Henansheng YongMo Technology Co., Ltd.",https://www.cantonfair.org.cn/en-US/shops/7805...,Hardware & Tools,NaN
3,"Foshan YouMi Electronic Technology Co., Ltd",https://www.cantonfair.org.cn/en-US/shops/8445...,Hardware & Tools,NaN
4,"GUANGDONG TOPCENT DEVELOPMENT CO.,LTD.",https://www.cantonfair.org.cn/en-US/shops/4516...,Hardware & Tools,NaN
...,...,...,...,...
21176,UNO KUNSHAN INDUSTRIAL INC.,https://www.cantonfair.org.cn/en-US/shops/4516...,Manufacturing,NaN
21177,"QINGYUAN JULI HOISTING MACHINERY CO.,LTD",https://www.cantonfair.org.cn/en-US/shops/4516...,Manufacturing,NaN
21178,"TAIZHOU XUTIAN PACKING MACHINE CO.,LTD",https://www.cantonfair.org.cn/en-US/shops/4516...,Manufacturing,NaN
21179,"CHONGQING LIFAN INDUSTRY(GROUP) IMP.&EXP.CO., LTD",https://www.cantonfair.org.cn/en-US/shops/4516...,Manufacturing,NaN
21180,"CHANGZHOU HUANGHE INTERNATIONAL TRADE CO.,LTD",https://www.cantonfair.org.cn/en-US/shops/4516...,Manufacturing,NaN