In [4]:
import os
os.chdir('/Users/rowena/Other Projects/external_data_study/Result/URA')

In [ ]:
import pdfplumber
import requests
import pandas as pd

url = "https://www.ura.org.hk/f/page/2679/18665/(Published)%20Notice%20of%20Tender%20and%20Award%20-%20Services_2026.02-2026.04.pdf"

# 1. Download the PDF locally
response = requests.get(url)
with open("service_tender_notice.pdf", "wb") as f:
    f.write(response.content)

# 2. Extract Table Data
all_data = []

with pdfplumber.open("service_tender_notice.pdf") as pdf:
    for page in pdf.pages:
        # Extract tables from the page
        table = page.extract_table()
        if table:
            # The first row of the first page is usually the header
            all_data.extend(table)

# 3. Clean and Save to CSV
# We skip the first row if it's a header and convert to a DataFrame
df = pd.DataFrame(all_data[1:], columns=all_data[0])
df.to_csv("ura_awards_service.csv", index=False)

print("Data successfully extracted to ura_awards.csv")

In [6]:
import pdfplumber
import requests
import pandas as pd

url = "https://www.ura.org.hk/f/page/2679/18665/(Published)%20Notice%20of%20Tender%20and%20Award%20-%20Services_2026.02-2026.04.pdf"

# 1. Download the PDF locally
response = requests.get(url)
with open("tender_notice.pdf", "wb") as f:
    f.write(response.content)

# 2. Extract Table Data
all_data = []

with pdfplumber.open("tender_notice.pdf") as pdf:
    for page in pdf.pages:
        # Extract tables from the page
        table = page.extract_table()
        if table:
            # The first row of the first page is usually the header
            all_data.extend(table)

# 3. Clean and Save to CSV
# We skip the first row if it's a header and convert to a DataFrame
df = pd.DataFrame(all_data[1:], columns=all_data[0])
df.to_csv("ura_awards_work.csv", index=False)

print("Data successfully extracted to ura_awards.csv")

Data successfully extracted to ura_awards.csv

In [7]:
df

,Project No.*\n(Location),Services Contracts\nType,Contract Title,Month of\nAward,Awarded\nContract Sum,Successful Tenderer
0,KC-017,Demolition Works,Phase 1 Hoarding and\nDemolition Works for Pro...,December\n2025,M3,Wing Fat Building\nConstruction Limited
1,H2,Improvement Works,Improvement Works for Project\nH2 - Western Ma...,November\n2025,M4,Woon Lee\nConstruction\nCompany Limited
2,SSP-018,Design and Build\nWorks,Design and Build of Joint-user\nComplex at Che...,October\n2025,M4,Hip Hing Engineering\nCompany Limited

In [13]:
import pandas as pd
import requests

url = "https://www.mtr.com.hk/en/corporate/tenders/Feb26.html"

# 1. Fetch the page content
header = {
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
}
response = requests.get(url, headers=header)

# 2. Use Pandas to find all tables on the page
# read_html returns a list of all tables found
tables = pd.read_html(response.text)

# 3. Identify the tender table (usually the first or only large table)
if tables:
    tender_df = tables[0]
    
    # Optional: Clean the data (e.g., removing newlines from addresses)
    tender_df = tender_df.replace(r'\n', ' ', regex=True)
    
    # 4. Save to CSV or Excel
    tender_df.to_csv("mtr_tenders_feb26.csv", index=False)
    print("Data extracted successfully!")
    print(tender_df.head())

Data extracted successfully!
  Reference No. Tendering Procedure  \
0       Q114692           Selective

                                      Title or Scope  \
0  Provision of Desludging of Sump Pits,Grease Tr...

                       Contractor(s) and Address(es)   Item/Quantity  \
0  Environmental Services Solutions Limited Unit ...  Not Applicable

  Awarded Amount Date Awarded
0   HK$3,587,200  10 Feb 2026

/var/folders/cc/fgdvcyz155z2b_s9qh66r2pw0000gn/T/ipykernel_4970/2995039137.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

In [11]:
tender_df

,Reference No.,Tendering Procedure,Title or Scope,Contractor(s) and Address(es),Item/Quantity,Awarded Amount,Date Awarded
0,C5043-25E,Selective,Replacement of AHUs and PAUs,Shinryo Technical Services Limited Room 1805 W...,Not Applicable,"HK$188,200,800",5 Jan 2026
1,Q106185,Selective,Provision of Catering Services for Staff Cante...,Asia Pacific Catering Corporation Limited 10/F...,3 Years,Not Disclosed,14 Jan 2026
2,Q114885,Selective,Term Contract for Provision of Printing Servic...,"Asia One Printing Limited 13/F, Asia One Tower...",3 Years,Not Disclosed,23 Jan 2026
3,Q115384,Selective,Provision of Train Components Washing Faciliti...,"Global Kleen HK Limited 8 Kai Fong Yuen, Ping ...",1 Job,"HK$3,861,564",8 Jan 2026
4,Q115667,Selective,Provision of Maintenance Services and Consumab...,"Anti-Mosquito Pro Limited Unit A, 1/F Bold Win...",Not Applicable,Not Applicable,28 Jan 2026